# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comments.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63omments.proto\"V\n\x15\x43reateCommentsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x1b\n\x06status\x18\x02 \x01(\x0e\x32\x0b.StatusEnum\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\")\n\x16\x43reateCommentsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08*5\n\nStatusEnum\x12\x0b\n\x07PENDING\x10\x00\x12\x0e\n\nPUBLISHING\x10\x01\x12\n\n\x06HIDING\x10\x02\x32\x45\n\x08\x43omments\x12\x39\n\x06\x43reate\x12\x16.CreateCommentsRequest\x1a\x17.CreateCommentsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comments_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUSENUM._serialized_start=149
  _STATUSENUM._serialized_end=202
  _CREATECOMMENTSREQUEST._serialized_start=18
  _CREATECOMMENTSREQUEST._serialized_end=104
  _CREATECOMMENTSRESPONSE._serialized_start=106
  _CREATECOMMENTSRESPONSE._serialized_end=147
  _COMMENTS._serialized_start=204
  _COMMENTS._serialized_end=273
# @@protoc_insertion_point(module_scope)
